const copy = {
  en: {
    skip:'Skip to content', navSystem:'The system', navInstall:'Installation', navPrivacy:'Privacy', navCta:'Discuss a pilot ↗',
    heroKicker:'Warehouse visibility / local-first concept', heroTitle:'See the work between arrival and departure.',
    heroLead:'A fixed camera can tell you when a truck arrived, which dock it used, where time was spent, and when it left. Edge Track turns those observations into a timeline your team can act on.',
    heroDemo:'Explore the scenario ↓', heroHow:'See how installation works ↗', heroNote:'Working laptop prototype. The on-site edge appliance is a proposed next step.',
    boardExample:'ILLUSTRATIVE VIEW', warehouse:'WAREHOUSE', legendTruck:'Truck track', legendZone:'Dock zone', boardLocal:'FRAMES PROCESSED ON SITE',
    signalOne:'Truck visits', signalOneDetail:'Arrival to exit', signalTwo:'Dock occupancy', signalTwoDetail:'When a bay is in use', signalThree:'Activity changes', signalThreeDetail:'Loading and idle periods inferred from movement',
    scenarioIndex:'SEE THE SIGNAL', scenarioTitle:'A visit becomes a timeline.', scenarioIntro:'Select an event to see how a dock visit is interpreted. This sequence is simulated and illustrates the rules, not a live camera feed.', simulationTag:'SIMULATED SCENARIO', yard:'YARD', dock:'DOCK 1', metricStatus:'Detected state', metricZone:'Zone', metricTime:'Visit time', controlsTitle:'Follow one truck', scenarioCaveat:'Events are inferred from tracked positions and configurable zones. A person crossing a loading line is only an activity proxy; it is not a verified pallet count.',
    systemIndex:'FROM IMAGE TO EVENT', systemTitle:'Keep the picture local. Use the event.', systemIntro:'The value is not another camera screen. It is a consistent record of visits, occupancy, and exceptions that can be reviewed by an operator.', methodOneTitle:'Observe', methodOneText:'A fixed view covers the yard approach and one or more loading docks. A camera or recorded clip supplies frames to the processor.', methodTwoTitle:'Track', methodTwoText:'Computer vision finds trucks and people, keeps short-lived track IDs, and checks their positions against drawn zones and crossing lines.', methodThreeTitle:'Understand', methodThreeText:'Rules turn those movements into arrival, dock entry, activity, idle, and exit events. The dashboard shows timings and lets you export visits.', methodFoot:'Today: laptop prototype tested with simulated sequences and public recorded video. Before a warehouse pilot: validate camera angles, detection accuracy, and any custom forklift model.',
    installIndex:'A PRACTICAL PILOT', installTitle:'Start with one camera and one dock.', installIntro:'The proposed installation uses your existing fixed camera where compatible. The pilot is a small, reversible setup: no warehouse-system integration is required to learn whether the view is useful.', installOneTitle:'Check the view', installOneText:'Choose a camera that clearly sees the truck approach, the dock threshold, and the loading area. Confirm image quality and permission to use the feed.', installTwoTitle:'Connect the processor', installTwoText:'Connect an on-site computer to power and the camera network. RTSP/IP-camera compatibility and edge hardware are verified during the pilot.', installThreeTitle:'Mark the zones', installThreeText:'Draw the yard and dock areas and a loading line on a sample frame. Set thresholds for brief occlusions and idle time.', installFourTitle:'Compare with reality', installFourText:'Run a short supervised trial, compare events with observed activity, adjust zones, then decide whether to expand to more cameras.', installCalloutTitle:'What you need for a first trial', installCalloutText:'One suitable fixed camera or a sample recording, local network access, a laptop or edge computer, and an operator who can verify the resulting timeline.',
    privacyIndex:'PRIVACY BY DESIGN', privacyTitle:'Process video. Do not build a video archive.', privacyLead:'The intended on-site setup analyzes live frames locally and does not save a continuous recording by default. What remains is a small operational event record: time, zone, track ID, and duration.', privacyCta:'Discuss privacy requirements for your site ↗', privacyOneTitle:'Camera frames', privacyOneText:'Processed on site in the proposed live setup. No continuous recording or cloud video upload is part of the default design.', privacyTwoTitle:'Offline imports', privacyTwoText:'The laptop prototype temporarily stores an imported video on the laptop while processing, then deletes that import when processing finishes or is cancelled.', privacyThreeTitle:'Event history', privacyThreeText:'Visit times and event metadata are retained locally for review and CSV export. Retention periods, access, and any optional review clips are decided with the pilot site.',
    limitsTitle:'What the prototype proves — and what it doesn’t.', limitsIntro:'A useful pilot starts with honest boundaries.', worksTitle:'Working today', worksText:'A local dashboard, configurable zones, truck and person tracking on recorded video, visit timelines, occupancy estimates, movement trails, and CSV export.', nextTitle:'Needs site validation', nextText:'Live camera integration, reliable forklift detection, pallet counts, camera-specific accuracy, multi-camera identity, and deployment on a dedicated edge device.',
    ctaIndex:'NEXT STEP', ctaTitle:'Have a dock worth measuring?', ctaText:'Tell us about one camera and one operational question. We can assess the view and define a small, privacy-conscious pilot.', ctaButton:'Discuss a pilot ↗', footerBy:'A Bitlads Software concept', footerBack:'Back to Bitlads Software ↗',
    states:[{time:'00:00',name:'Truck arrives',state:'Arrival detected',zone:'Yard',duration:'00:00',badge:'ARRIVAL / YARD'}, {time:'03:12',name:'Enters dock 1',state:'Dock occupied',zone:'Dock 1',duration:'03:12',badge:'DOCK 1 / OCCUPIED'}, {time:'08:46',name:'Activity at dock',state:'Activity inferred',zone:'Dock 1',duration:'08:46',badge:'CROSSING / ACTIVITY'}, {time:'37:30',name:'Truck exits',state:'Visit complete',zone:'Outside',duration:'37:30',badge:'EXIT / VISIT COMPLETE'}],
    title:'Edge Track — See the work between arrival and departure', description:'Edge Track turns fixed-camera warehouse footage into dock occupancy, truck visits and activity events. Local-first concept by Bitlads Software.'
  },
  ro: {
    skip:'Sari la conținut', navSystem:'Cum funcționează', navInstall:'Instalare', navPrivacy:'Confidențialitate', navCta:'Discută un proiect-pilot ↗',
    heroKicker:'Vizibilitate în depozit / concept cu procesare locală', heroTitle:'Vezi ce se întâmplă între sosire și plecare.',
    heroLead:'O cameră fixă poate arăta când a sosit un camion, ce rampă a folosit, unde s-a consumat timpul și când a plecat. Edge Track transformă aceste observații într-o cronologie utilă echipei.',
    heroDemo:'Explorează scenariul ↓', heroHow:'Vezi cum se instalează ↗', heroNote:'Prototip funcțional pe laptop. Dispozitivul edge instalat la fața locului este pasul propus următor.',
    boardExample:'VIZUALIZARE ILUSTRATIVĂ', warehouse:'DEPOZIT', legendTruck:'Traseu camion', legendZone:'Zonă rampă', boardLocal:'CADRE PROCESATE LOCAL',
    signalOne:'Vizite camioane', signalOneDetail:'De la sosire la plecare', signalTwo:'Ocuparea rampelor', signalTwoDetail:'Când este folosită o rampă', signalThree:'Schimbări de activitate', signalThreeDetail:'Încărcare și pauze deduse din mișcare',
    scenarioIndex:'VEZI SEMNALUL', scenarioTitle:'O vizită devine o cronologie.', scenarioIntro:'Selectează un eveniment ca să vezi cum este interpretată vizita la rampă. Secvența este simulată și ilustrează regulile; nu este o transmisie video live.', simulationTag:'SCENARIU SIMULAT', yard:'CURTE', dock:'RAMPA 1', metricStatus:'Stare detectată', metricZone:'Zonă', metricTime:'Durata vizitei', controlsTitle:'Urmărește un camion', scenarioCaveat:'Evenimentele sunt deduse din poziții urmărite și zone configurabile. Trecerea unei persoane peste linia de încărcare este doar un indicator de activitate, nu un număr de paleți verificat.',
    systemIndex:'DIN IMAGINE ÎN EVENIMENT', systemTitle:'Păstrezi imaginea local. Folosești evenimentul.', systemIntro:'Valoarea nu este încă un ecran cu camere. Este o evidență consecventă a vizitelor, ocupării și excepțiilor, pe care un operator o poate verifica.', methodOneTitle:'Observă', methodOneText:'O cameră fixă acoperă accesul în curte și una sau mai multe rampe. Camera sau un clip înregistrat furnizează cadrele pentru procesare.', methodTwoTitle:'Urmărește', methodTwoText:'Viziunea computerizată detectează camioane și persoane, menține identificatori temporari și verifică poziția lor față de zonele și liniile desenate.', methodThreeTitle:'Înțelege', methodThreeText:'Regulile transformă mișcarea în evenimente de sosire, intrare la rampă, activitate, pauză și ieșire. Panoul afișează timpii și permite exportul vizitelor.', methodFoot:'Astăzi: prototip pe laptop testat cu secvențe simulate și înregistrări video publice. Înaintea unui proiect-pilot: verificăm unghiurile camerelor, precizia detecției și orice model personalizat pentru stivuitoare.',
    installIndex:'UN PILOT PRACTIC', installTitle:'Începi cu o cameră și o rampă.', installIntro:'Instalarea propusă folosește, dacă este compatibilă, o cameră fixă deja existentă. Pilotul este mic și reversibil: nu ai nevoie de integrare cu sistemele depozitului ca să vezi dacă informația este utilă.', installOneTitle:'Verifică imaginea', installOneText:'Alege o cameră care vede clar accesul camionului, pragul rampei și zona de încărcare. Confirmă calitatea imaginii și dreptul de a folosi fluxul video.', installTwoTitle:'Conectează procesorul', installTwoText:'Conectează un calculator local la curent și la rețeaua camerelor. Compatibilitatea RTSP/cameră IP și hardware-ul edge se verifică în pilot.', installThreeTitle:'Marchează zonele', installThreeText:'Desenează curtea, rampele și o linie de încărcare pe un cadru de probă. Configurează pragurile pentru obturări scurte și timpul de inactivitate.', installFourTitle:'Compară cu realitatea', installFourText:'Rulează un test scurt supravegheat, compară evenimentele cu activitatea observată, ajustează zonele și apoi decizi dacă extinzi la alte camere.', installCalloutTitle:'Ce îți trebuie la primul test', installCalloutText:'O cameră fixă potrivită sau o înregistrare de probă, acces la rețeaua locală, un laptop ori calculator edge și un operator care poate verifica rezultatele.',
    privacyIndex:'CONFIDENȚIALITATE DIN DESIGN', privacyTitle:'Procesezi video. Nu creezi o arhivă video.', privacyLead:'Sistemul local propus analizează cadrele live la fața locului și nu salvează implicit o înregistrare continuă. Rămâne o evidență operațională restrânsă: timp, zonă, ID temporar și durată.', privacyCta:'Discută cerințele de confidențialitate ale locației ↗', privacyOneTitle:'Cadrele camerei', privacyOneText:'Procesate la fața locului în varianta live propusă. Înregistrarea continuă și încărcarea video în cloud nu fac parte din configurația implicită.', privacyTwoTitle:'Importuri offline', privacyTwoText:'Prototipul pe laptop stochează temporar fișierul importat pe laptop cât timp îl procesează, apoi îl șterge la final sau la anularea procesării.', privacyThreeTitle:'Istoricul evenimentelor', privacyThreeText:'Timpii vizitelor și metadatele evenimentelor rămân local pentru verificare și export CSV. Perioada de păstrare, accesul și eventualele clipuri opționale se stabilesc împreună cu locația-pilot.',
    limitsTitle:'Ce demonstrează prototipul — și ce nu.', limitsIntro:'Un pilot util începe cu limite clare.', worksTitle:'Funcționează acum', worksText:'Panou local, zone configurabile, urmărirea camioanelor și persoanelor pe video înregistrat, cronologia vizitelor, estimări de ocupare, trasee colorate și export CSV.', nextTitle:'Necesită validare la fața locului', nextText:'Integrarea camerei live, detectarea fiabilă a stivuitoarelor, numărarea paleților, precizia pentru fiecare cameră, identificarea între camere și rularea pe un dispozitiv edge dedicat.',
    ctaIndex:'PASUL URMĂTOR', ctaTitle:'Ai o rampă pe care vrei să o măsori?', ctaText:'Spune-ne ce cameră ai și la ce întrebare operațională vrei un răspuns. Putem evalua imaginea și defini un pilot mic, atent la confidențialitate.', ctaButton:'Discută un proiect-pilot ↗', footerBy:'Un concept Bitlads Software', footerBack:'Înapoi la Bitlads Software ↗',
    states:[{time:'00:00',name:'Camionul sosește',state:'Sosire detectată',zone:'Curte',duration:'00:00',badge:'SOSIRE / CURTE'}, {time:'03:12',name:'Intră la rampa 1',state:'Rampă ocupată',zone:'Rampa 1',duration:'03:12',badge:'RAMPA 1 / OCUPATĂ'}, {time:'08:46',name:'Activitate la rampă',state:'Activitate dedusă',zone:'Rampa 1',duration:'08:46',badge:'TRECERE / ACTIVITATE'}, {time:'37:30',name:'Camionul pleacă',state:'Vizită încheiată',zone:'Exterior',duration:'37:30',badge:'PLECARE / VIZITĂ ÎNCHEIATĂ'}],
    title:'Edge Track — Vezi ce se întâmplă între sosire și plecare', description:'Edge Track transformă imagini de la o cameră fixă în vizite ale camioanelor, ocuparea rampelor și evenimente de activitate. Concept Bitlads Software cu procesare locală.'
  }
};
let lang = new URLSearchParams(location.search).get('lang') === 'ro' ? 'ro' : 'en';
let step = 0;
const eventList = document.getElementById('event-list');
function renderStep(){
  const items = copy[lang].states;
  const selected = items[step];
  document.getElementById('stage').className = `scenario-stage stage-${step}`;
  document.getElementById('stage-state').textContent = selected.badge;
  document.getElementById('metric-status').textContent = selected.state;
  document.getElementById('metric-zone').textContent = selected.zone;
  document.getElementById('metric-time').textContent = selected.duration;
  eventList.replaceChildren();
  items.forEach((item, index) => {
    const button = document.createElement('button');
    button.type = 'button'; button.className = 'event-button'; button.setAttribute('aria-pressed', String(index === step));
    const time = document.createElement('span'); time.className = 'event-time'; time.textContent = item.time;
    const name = document.createElement('span'); name.className = 'event-name'; name.textContent = item.name;
    const arrow = document.createElement('span'); arrow.className = 'event-arrow'; arrow.setAttribute('aria-hidden','true'); arrow.textContent = '↗';
    button.append(time,name,arrow); button.addEventListener('click',()=>{step=index;renderStep()}); eventList.append(button);
  });
}
function render(){
  const t = copy[lang];
  document.documentElement.lang = lang;
  document.title = t.title;
  document.querySelector('meta[name="description"]').content = t.description;
  document.querySelector('meta[property="og:title"]').content = t.title;
  document.querySelector('meta[property="og:description"]').content = t.description;
  document.querySelectorAll('[data-i18n]').forEach(node => { node.textContent = t[node.dataset.i18n]; });
  document.querySelectorAll('[data-lang]').forEach(button => button.setAttribute('aria-pressed',String(button.dataset.lang === lang)));
  renderStep();
}
document.querySelectorAll('[data-lang]').forEach(button => button.addEventListener('click',()=>{
  lang = button.dataset.lang;
  const url = new URL(location.href);
  if(lang==='ro')url.searchParams.set('lang','ro');else url.searchParams.delete('lang');
  history.replaceState(null,'',url);
  render();
}));
window.addEventListener('popstate',()=>{lang=new URLSearchParams(location.search).get('lang')==='ro'?'ro':'en';render()});
document.getElementById('year').textContent = new Date().getFullYear();
render();
